import React, { useState, useEffect } from "react";
import "./App.css";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import axios from "axios";
import { Button } from "./components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./components/ui/card";
import { Badge } from "./components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs";
import { AlertCircle, Database, TrendingUp, MapPin, Play, Loader2, Download } from "lucide-react";
import { Alert, AlertDescription } from "./components/ui/alert";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const Dashboard = () => {
  const [scrapingSessions, setScrapingSessions] = useState([]);
  const [properties, setProperties] = useState([]);
  const [regionStats, setRegionStats] = useState([]);
  const [loading, setLoading] = useState(false);
  const [currentSession, setCurrentSession] = useState(null);

  const fetchScrapingSessions = async () => {
    try {
      const response = await axios.get(`${API}/scraping-sessions`);
      setScrapingSessions(response.data);
    } catch (error) {
      console.error('Error fetching sessions:', error);
    }
  };

  const fetchProperties = async () => {
    try {
      const response = await axios.get(`${API}/properties?limit=50`);
      setProperties(response.data);
    } catch (error) {
      console.error('Error fetching properties:', error);
    }
  };

  const fetchRegionStats = async () => {
    try {
      const response = await axios.get(`${API}/stats/regions`);
      setRegionStats(response.data);
    } catch (error) {
      console.error('Error fetching stats:', error);
    }
  };

  const startScraping = async () => {
    try {
      setLoading(true);
      const response = await axios.post(`${API}/scrape/start`);
      setCurrentSession(response.data.session_id);
      
      // Poll for session updates
      const pollInterval = setInterval(async () => {
        try {
          const sessionResponse = await axios.get(`${API}/scraping-sessions/${response.data.session_id}`);
          const session = sessionResponse.data;
          
          if (session.status === 'completed' || session.status === 'failed') {
            clearInterval(pollInterval);
            setLoading(false);
            setCurrentSession(null);
            fetchScrapingSessions();
            fetchProperties();
            fetchRegionStats();
          }
        } catch (error) {
          console.error('Error polling session:', error);
          clearInterval(pollInterval);
          setLoading(false);
        }
      }, 5000);
      
    } catch (error) {
      console.error('Error starting scraping:', error);
      setLoading(false);
    }
  };

  const exportPhpData = async () => {
    try {
      const response = await axios.get(`${API}/export/php`);
      const phpCode = generatePhpCode(response.data.php_array);
      
      // Create downloadable file
      const blob = new Blob([phpCode], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'market_data.php';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error exporting PHP data:', error);
    }
  };

  const generatePhpCode = (data) => {
    const timestamp = new Date().toLocaleString('pt-PT');
    
    let phpCode = `<?php
/**
 * Market prices data for Portugal
 * Last update ${timestamp}
 * Generated by Idealista Scraper
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Get market data for Portuguese real estate
 *
 * @return array Market data by region
 */
function tagus_value_get_market_data() {
    return ${phpArrayToString(data, 1)};
}
`;
    return phpCode;
  };

  const phpArrayToString = (obj, indent = 0) => {
    const spaces = '    '.repeat(indent);
    if (Array.isArray(obj)) {
      return 'array()';
    }
    
    let result = 'array(\n';
    for (const [key, value] of Object.entries(obj)) {
      result += `${spaces}    '${key}' => `;
      if (typeof value === 'object' && value !== null) {
        result += phpArrayToString(value, indent + 1);
      } else if (typeof value === 'string') {
        result += `'${value}'`;
      } else {
        result += value;
      }
      result += ',\n';
    }
    result += `${spaces})`;
    return result;
  };

  const clearAllData = async () => {
    try {
      await axios.delete(`${API}/properties`);
      setProperties([]);
      setRegionStats([]);
    } catch (error) {
      console.error('Error clearing data:', error);
    }
  };

  useEffect(() => {
    fetchScrapingSessions();
    fetchProperties();
    fetchRegionStats();
  }, []);

  const formatCurrency = (value) => {
    if (!value) return '€0';
    return new Intl.NumberFormat('pt-PT', {
      style: 'currency',
      currency: 'EUR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-6">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Idealista Portugal Scraper
          </h1>
          <p className="text-xl text-gray-600">
            Monitor Portuguese real estate market prices from idealista.pt
          </p>
        </div>

        {/* Control Panel */}
        <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Database className="h-5 w-5 text-blue-600" />
              Scraping Control Panel
            </CardTitle>
            <CardDescription>
              Start scraping real estate prices from all Portuguese regions
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-4 flex-wrap">
              <Button
                onClick={startScraping}
                disabled={loading}
                className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800"
              >
                {loading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Scraping...
                  </>
                ) : (
                  <>
                    <Play className="h-4 w-4 mr-2" />
                    Start Scraping
                  </>
                )}
              </Button>
              
              <Button onClick={exportPhpData} variant="outline">
                <Download className="h-4 w-4 mr-2" />
                Export PHP Data
              </Button>
              
              <Button onClick={clearAllData} variant="outline" className="text-red-600 hover:text-red-700">
                Clear All Data
              </Button>
            </div>
            
            {loading && (
              <Alert>
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  Scraping in progress... This may take several minutes to complete.
                </AlertDescription>
              </Alert>
            )}
          </CardContent>
        </Card>

        {/* Main Content */}
        <Tabs defaultValue="overview" className="space-y-6">
          <TabsList className="grid w-full grid-cols-4 bg-white/50 backdrop-blur-sm">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="sessions">Scraping Sessions</TabsTrigger>
            <TabsTrigger value="properties">Properties</TabsTrigger>
            <TabsTrigger value="stats">Regional Stats</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-gray-600">Total Properties</p>
                      <p className="text-2xl font-bold text-gray-900">{properties.length}</p>
                    </div>
                    <Database className="h-8 w-8 text-blue-600" />
                  </div>
                </CardContent>
              </Card>

              <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-gray-600">Regions Covered</p>
                      <p className="text-2xl font-bold text-gray-900">{regionStats.length}</p>
                    </div>
                    <MapPin className="h-8 w-8 text-green-600" />
                  </div>
                </CardContent>
              </Card>

              <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-gray-600">Scraping Sessions</p>
                      <p className="text-2xl font-bold text-gray-900">{scrapingSessions.length}</p>
                    </div>
                    <TrendingUp className="h-8 w-8 text-purple-600" />
                  </div>
                </CardContent>
              </Card>
            </div>

            {regionStats.length > 0 && (
              <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle>Quick Regional Overview</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {regionStats.slice(0, 6).map((stat, index) => (
                      <div key={index} className="p-4 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg">
                        <h4 className="font-semibold capitalize text-gray-900">{stat.region} - {stat.location}</h4>
                        <div className="space-y-1 text-sm">
                          <p>Avg Sale: {formatCurrency(stat.avg_sale_price)}</p>
                          <p>Avg Rent: {formatCurrency(stat.avg_rent_price)}</p>
                          <p>Properties: {stat.total_properties}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          <TabsContent value="sessions">
            <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
              <CardHeader>
                <CardTitle>Scraping Sessions History</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {scrapingSessions.map((session) => (
                    <div key={session.id} className="p-4 border rounded-lg bg-white/50">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="font-medium">Session {session.id.slice(0, 8)}</p>
                          <p className="text-sm text-gray-600">
                            Started: {new Date(session.started_at).toLocaleString('pt-PT')}
                          </p>
                          {session.completed_at && (
                            <p className="text-sm text-gray-600">
                              Completed: {new Date(session.completed_at).toLocaleString('pt-PT')}
                            </p>
                          )}
                        </div>
                        <div className="text-right">
                          <Badge
                            variant={
                              session.status === 'completed' ? 'default' :
                              session.status === 'running' ? 'secondary' : 'destructive'
                            }
                          >
                            {session.status}
                          </Badge>
                          <p className="text-sm text-gray-600 mt-1">
                            {session.total_properties} properties
                          </p>
                        </div>
                      </div>
                      {session.error_message && (
                        <Alert className="mt-3">
                          <AlertCircle className="h-4 w-4" />
                          <AlertDescription>{session.error_message}</AlertDescription>
                        </Alert>
                      )}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="properties">
            <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
              <CardHeader>
                <CardTitle>Recent Properties</CardTitle>
                <CardDescription>Latest scraped properties from idealista.pt</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {properties.slice(0, 12).map((property) => (
                    <div key={property.id} className="p-4 border rounded-lg bg-white/50 hover:bg-white/70 transition-colors">
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <Badge variant="outline" className="capitalize">
                            {property.property_type}
                          </Badge>
                          <Badge variant={property.operation_type === 'sale' ? 'default' : 'secondary'}>
                            {property.operation_type}
                          </Badge>
                        </div>
                        <h4 className="font-medium capitalize">
                          {property.region} - {property.location}
                        </h4>
                        <div className="space-y-1 text-sm text-gray-600">
                          {property.price && (
                            <p>Price: {formatCurrency(property.price)}</p>
                          )}
                          {property.area && (
                            <p>Area: {property.area} m²</p>
                          )}
                          {property.price_per_sqm && (
                            <p>€/m²: {formatCurrency(property.price_per_sqm)}</p>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="stats">
            <Card className="border-0 shadow-lg bg-white/70 backdrop-blur-sm">
              <CardHeader>
                <CardTitle>Regional Statistics</CardTitle>
                <CardDescription>Aggregated market data by region and location</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {regionStats.map((stat, index) => (
                    <div key={index} className="p-6 border rounded-lg bg-gradient-to-r from-blue-50 to-purple-50">
                      <h4 className="font-bold text-lg capitalize mb-4">
                        {stat.region} - {stat.location}
                      </h4>
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <p className="text-sm font-medium text-gray-600">Sale Prices</p>
                          <p className="text-xl font-bold text-blue-700">
                            {formatCurrency(stat.avg_sale_price)}
                          </p>
                          {stat.avg_price_per_sqm_sale && (
                            <p className="text-sm text-gray-500">
                              {formatCurrency(stat.avg_price_per_sqm_sale)}/m²
                            </p>
                          )}
                        </div>
                        <div>
                          <p className="text-sm font-medium text-gray-600">Rental Prices</p>
                          <p className="text-xl font-bold text-green-700">
                            {formatCurrency(stat.avg_rent_price)}
                          </p>
                          {stat.avg_price_per_sqm_rent && (
                            <p className="text-sm text-gray-500">
                              {formatCurrency(stat.avg_price_per_sqm_rent)}/m²
                            </p>
                          )}
                        </div>
                      </div>
                      <div className="mt-4 pt-4 border-t">
                        <p className="text-sm text-gray-600">
                          Total Properties: <span className="font-medium">{stat.total_properties}</span>
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Dashboard />} />
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;